version: '2.2'
services:
  lgogwebui:
    build: .
    image: graag/lgogwebui
    container_name: lgogwebui
    volumes:
      - "$HOME/.cache/lgogdownloader:/home/user/.cache/lgogdownloader"
      - "$HOME/.config/lgogdownloader:/home/user/.config/lgogdownloader"
      - "$GOG_DIR:/home/user/GOG"
    networks:
      - lgogwebui
    environment:
      LOCAL_USER_ID: "$UID"
      SCRIPT_NAME: "${SCRIPT_NAME:-}"
    restart: always
  web:
    image: nginx
    container_name: lgogwebui_proxy
    volumes:
      - ./nginx/lgogwebui.template:/etc/nginx/conf.d/lgogwebui.template
      - ./nginx/run.sh:/opt/run.sh
    networks:
      - lgogwebui
    ports:
      - "${NGINX_PORT:-8080}:443"
    environment:
      - NGINX_HOST=$HOSTNAME
      - NGINX_PORT=$NGINX_PORT
    command: /bin/bash -c "/opt/run.sh"
    restart: always
networks:
  lgogwebui:
    driver: bridge
